---

- name: apt-get update and install nginx-full
  apt: name=nginx-full state=latest update_cache=true
  register: nginxinstalled
  notify:
      - start nginx

- name: apt-get install nginx-extras
  apt: name=nginx-full state=latest update_cache=false
  notify:
      - reload nginx

- name: nginx instalation failed
  when: nginxinstalled|failed
  fail: msg="nginx instalation failed, please check logs"

- name: push nginx.conf template
  when: nginxinstalled|success
  template: src=roles/nginx/templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0640

- name: push snippets template
  when: nginxinstalled|success
  copy: src=roles/nginx/files/blockuseragents.rules dest=/etc/nginx/snippets/blockuseragents.rules mode=0640

- name: push site configuration template
  when: nginxinstalled|success
  template: src=roles/nginx/templates/virtualhost.j2 dest=/etc/nginx/sites-available/{{ domain }} mode=0640

- name: create document root
  when: nginxinstalled|success
  file: dest=/var/www/{{ domain }} mode=755 state=directory owner=root group=www-data

- name: document root permissions
  when: nginxinstalled|success
  file: dest=/var/www/{{ domain }} mode=755 state=directory owner=root group=www-data recurse=yes

- name: check nginx config
  when: nginxinstalled|success
  command: /usr/sbin/nginx -t
  register: nginxconfig 

- name: nginx config error
  when: nginxconfig|failed
  fail: msg="nginx config error, check your config..."

- name: disable default virtualhost
  when: nginxconfig|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: enable site
  when: nginxconfig|success
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  notify:
    - reload nginx



     
