---

- name: Install awscli 
  apt: pkg=awscli install_recommends=yes update_cache=yes 
  register: awsinstalled

- name: Ensure .aws/ dir exists
  file: path=~/.aws/ owner=root group=root mode=600 state=directory follow=yes

- name: Ensure .cron/ dir exists
  file: path=~/.cron/ owner=root group=root mode=700 state=directory follow=yes

- name: Copy access_key and secret_key
  when: awsinstalled|success
  template: src=roles/backup/templates/config.j2 dest=~/.aws/config owner=root group=root mode=600 

- name: Ensure bucket exists
  s3_bucket:
    name: "{{ s3_bucket }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_access_secret }}"
    state: present

- name: Copy backup script
  when: awsinstalled|success
  template: src=roles/backup/templates/backup.sh.j2 dest=~/.cron/backup.sh owner=root group=root mode=700 
