---

- name: Ensure document root exists
  file: path="/var/www{{ phpmyadmin_domain_name }}" state=directory follow=yes
  register: docrootexist

- name: Document root doesn't exists
  when: docrootexist|failed
  file: dest="/var/www{{ phpmyadmin_domain_name }}" mode=755 state=directory owner=root group=www-data

- name: download phpmyadmin
  git: repo={{ phpmyadmin_repo }} depth=1 version=STABLE dest=/var/www/{{ phpmyadmin_domain_name }}
  register: phpmyadminDownloaded

- name: add phpmyadmin virtualhost
  when: phpmyadminDownloaded|success
  template: src=roles/phpmyadmin/templates/phpmyadmin.j2 dest=/etc/nginx/sites-available/phpmyadmin mode=0640

- name: enable phpmyadmin
  when: phpmyadminDownloaded|success
  file: src=/etc/nginx/sites-available/phpmyadmin dest=/etc/nginx/sites-enabled/phpmyadmin state=link
  notify:
    - reload nginx



