---
- name: installs common utilities
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
      - vim
      - wget
      - curl
      - htop
      - git
      - drush
      - python-pexpect
      - python-pip
      - python-boto
      
